spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.yaml
server.servlet.context-path=/api

jwt.expiration=300000
jwt.secret=abracadabra#546565744352fsfjkn$#^#$%#$465465466445$#@@DFG
